# Generated by Django 2.2.10 on 2020-03-01 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nivelDeConfidencialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_nivel_confidencialidad', models.CharField(default=None, help_text='Descripción del Nivel de Confidencialidad', max_length=50, verbose_name='Descripción del Nivel de Confidencialidad')),
                ('nivel_confidencialidad', models.IntegerField(default=0, help_text='100 - Mayor de Nivel de Acceso, 0 - Nulo nivel de acceso', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Nivel de Confidencialidad')),
                ('activo', models.BooleanField(default=True, help_text='Estado Lógico del Registro (Activo/Inactivo)', verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Niveles de Confidencialidad',
                'ordering': ('nivel_confidencialidad', 'descripcion_nivel_confidencialidad'),
            },
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('nivel', 'nombre')},
        ),
    ]
