# Generated by Django 2.2.10 on 2020-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modadmin', '0002_auto_20200228_0442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ('job_position_description',), 'verbose_name_plural': 'Perfiles de Puestos'},
        ),
        migrations.RenameField(
            model_name='jobposition',
            old_name='jobposition',
            new_name='department_default',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='jobposition_name',
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado Lógico del Registro (Activo|Inactivo)', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='job_position_description',
            field=models.CharField(default='DIRECTOR', help_text='Descripción del Perfil de Puesto', max_length=150, verbose_name='Descripción del Nivel de Confidencialidad'),
        ),
    ]
